### ISSUE TITLE
production build broken

### ISSUE THREAD

**Issue by Havunen** [ivijs/boilerplate#2]
Cloning repository, installing packages and running `npm run dist`  results into following error:
```
^Csk@sk-ubuntu:~/git/boilerplate$ npm run dist

> ivi-boilerplate@1.0.0 dist /home/sk/git/boilerplate
> webpack --config webpack.prod.config.js

ts-loader: Using typescript@2.4.2 and /home/sk/git/boilerplate/tsconfig.json
Caught error:  Error: bundle.js from Closure Compiler
The compiler is waiting for input via stdin.
stdin:855: ERROR - variable DEV_MODE is undeclared
        if ((DEV_MODE & 2 /* DisableStackTraceAugmentation */) === 0) {
             ^^^^^^^^

stdin:993: ERROR - variable getFunctionName is undeclared
                        console.groupCollapsed(`[C]${getFunctionName(cls)} #${instance._debugId}`);
                                                     ^^^^^^^^^^^^^^^

stdin:1081: ERROR - variable printComponentStackTrace is undeclared
        printComponentStackTrace();
        ^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1245: ERROR - variable nextDebugId is undeclared
            this._debugId = nextDebugId();
                            ^^^^^^^^^^^

stdin:1428: ERROR - variable printWarnOnce is undeclared
                    printWarnOnce(`typo.attribute.${attrName}`, msg);
                    ^^^^^^^^^^^^^

stdin:1457: ERROR - variable printWarn is undeclared
                        printWarn(`Typo: style "${styleName}" has a value with a newline character "${styleValue}".`);
                        ^^^^^^^^^

stdin:1587: ERROR - variable checkDOMStylesForTypos is undeclared
                checkDOMStylesForTypos(style);
                ^^^^^^^^^^^^^^^^^^^^^^

stdin:1637: ERROR - variable checkDOMAttributesForTypos is undeclared
                checkDOMAttributesForTypos(props);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1639: ERROR - variable checkDeprecatedDOMSVGAttributes is undeclared
                    checkDeprecatedDOMSVGAttributes(this._tag, props);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1843: ERROR - variable isInputTypeHasCheckedProperty is undeclared
            if (!isInputTypeHasCheckedProperty(this._tag)) {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1990: ERROR - variable isComponentClass is undeclared
        if (isComponentClass(render)) {
            ^^^^^^^^^^^^^^^^

stdin:1992: ERROR - variable VNode is undeclared
                return new VNode(8 /* ComponentClass */, render, props, null, null);
                           ^^^^^

stdin:4115: ERROR - variable perfMarkBegin is undeclared
            perfMarkBegin(id);
            ^^^^^^^^^^^^^

stdin:4132: ERROR - variable perfMarkEnd is undeclared
                perfMarkEnd(`${method} [C]${getFunctionName(cls)}`, id);
                ^^^^^^^^^^^

stdin:4168: ERROR - variable setInitialNestingState is undeclared
        setInitialNestingState(parent);
        ^^^^^^^^^^^^^^^^^^^^^^

stdin:4173: ERROR - variable stackTraceAugment is undeclared
            stackTraceAugment(e);
            ^^^^^^^^^^^^^^^^^

stdin:4174: ERROR - variable devModeOnError is undeclared
            devModeOnError(e);
            ^^^^^^^^^^^^^^

stdin:4175: ERROR - variable stackTraceReset is undeclared
            stackTraceReset();
            ^^^^^^^^^^^^^^^

stdin:4779: ERROR - variable pushNestingState is undeclared
                        pushNestingState(vnode._tag);
                        ^^^^^^^^^^^^^^^^

stdin:4780: ERROR - variable checkNestingViolation is undeclared
                        checkNestingViolation();
                        ^^^^^^^^^^^^^^^^^^^^^

stdin:6108: ERROR - variable ROOTS is undeclared
        for (const root of ROOTS) {
                           ^^^^^

stdin:6127: ERROR - variable getDOMInstanceFromVNode is undeclared
                return node === getDOMInstanceFromVNode(vnode._children);
                                ^^^^^^^^^^^^^^^^^^^^^^^

stdin:6235: ERROR - variable VERSION is undeclared
    console.info(`IVI [${VERSION}]: DEVELOPMENT MODE`);
                         ^^^^^^^

stdin:6247: ERROR - variable printError is undeclared
        printError("`Array.isArray` function is missing.");
        ^^^^^^^^^^

stdin:6262: ERROR - variable FEATURES is undeclared
        console.groupCollapsed(`${((FEATURES & flag) ? "✔" : "✖")} ${name}`);
                                    ^^^^^^^^

stdin:6286: ERROR - variable findVNodeByDebugId is undeclared
        "findVNodeByDebugId": findVNodeByDebugId,
                              ^^^^^^^^^^^^^^^^^^

stdin:6287: ERROR - variable findVNodeByNode is undeclared
        "findVNodeByNode": findVNodeByNode,
                           ^^^^^^^^^^^^^^^

stdin:6290: ERROR - variable visitComponents is undeclared
                visitComponents(_printComponentTreeVisitor);
                ^^^^^^^^^^^^^^^

stdin:6309: ERROR - variable GLOBAL_EXPORT is undeclared
    if (GLOBAL_EXPORT && !window.hasOwnProperty(GLOBAL_EXPORT)) {
        ^^^^^^^^^^^^^

29 error(s), 0 warning(s)

    at /home/sk/git/boilerplate/node_modules/webpack-closure-compiler/index.js:72:20
    at ChildProcess.<anonymous> (/home/sk/git/boilerplate/node_modules/webpack-closure-compiler/lib/runner.js:70:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Hash: 805e872401f0274b6a1f
Version: webpack 3.5.5
Time: 3354ms
    Asset    Size  Chunks             Chunk Names
bundle.js  247 kB       0  [emitted]  main
   [0] ./src/main.ts + 51 modules 249 kB {0} [built]

ERROR in bundle.js from Closure Compiler
The compiler is waiting for input via stdin.
stdin:855: ERROR - variable DEV_MODE is undeclared
        if ((DEV_MODE & 2 /* DisableStackTraceAugmentation */) === 0) {
             ^^^^^^^^

stdin:993: ERROR - variable getFunctionName is undeclared
                        console.groupCollapsed(`[C]${getFunctionName(cls)} #${instance._debugId}`);
                                                     ^^^^^^^^^^^^^^^

stdin:1081: ERROR - variable printComponentStackTrace is undeclared
        printComponentStackTrace();
        ^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1245: ERROR - variable nextDebugId is undeclared
            this._debugId = nextDebugId();
                            ^^^^^^^^^^^

stdin:1428: ERROR - variable printWarnOnce is undeclared
                    printWarnOnce(`typo.attribute.${attrName}`, msg);
                    ^^^^^^^^^^^^^

stdin:1457: ERROR - variable printWarn is undeclared
                        printWarn(`Typo: style "${styleName}" has a value with a newline character "${styleValue}".`);
                        ^^^^^^^^^

stdin:1587: ERROR - variable checkDOMStylesForTypos is undeclared
                checkDOMStylesForTypos(style);
                ^^^^^^^^^^^^^^^^^^^^^^

stdin:1637: ERROR - variable checkDOMAttributesForTypos is undeclared
                checkDOMAttributesForTypos(props);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1639: ERROR - variable checkDeprecatedDOMSVGAttributes is undeclared
                    checkDeprecatedDOMSVGAttributes(this._tag, props);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1843: ERROR - variable isInputTypeHasCheckedProperty is undeclared
            if (!isInputTypeHasCheckedProperty(this._tag)) {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin:1990: ERROR - variable isComponentClass is undeclared
        if (isComponentClass(render)) {
            ^^^^^^^^^^^^^^^^

stdin:1992: ERROR - variable VNode is undeclared
                return new VNode(8 /* ComponentClass */, render, props, null, null);
                           ^^^^^

stdin:4115: ERROR - variable perfMarkBegin is undeclared
            perfMarkBegin(id);
            ^^^^^^^^^^^^^

stdin:4132: ERROR - variable perfMarkEnd is undeclared
                perfMarkEnd(`${method} [C]${getFunctionName(cls)}`, id);
                ^^^^^^^^^^^

stdin:4168: ERROR - variable setInitialNestingState is undeclared
        setInitialNestingState(parent);
        ^^^^^^^^^^^^^^^^^^^^^^

stdin:4173: ERROR - variable stackTraceAugment is undeclared
            stackTraceAugment(e);
            ^^^^^^^^^^^^^^^^^

stdin:4174: ERROR - variable devModeOnError is undeclared
            devModeOnError(e);
            ^^^^^^^^^^^^^^

stdin:4175: ERROR - variable stackTraceReset is undeclared
            stackTraceReset();
            ^^^^^^^^^^^^^^^

stdin:4779: ERROR - variable pushNestingState is undeclared
                        pushNestingState(vnode._tag);
                        ^^^^^^^^^^^^^^^^

stdin:4780: ERROR - variable checkNestingViolation is undeclared
                        checkNestingViolation();
                        ^^^^^^^^^^^^^^^^^^^^^

stdin:6108: ERROR - variable ROOTS is undeclared
        for (const root of ROOTS) {
                           ^^^^^

stdin:6127: ERROR - variable getDOMInstanceFromVNode is undeclared
                return node === getDOMInstanceFromVNode(vnode._children);
                                ^^^^^^^^^^^^^^^^^^^^^^^

stdin:6235: ERROR - variable VERSION is undeclared
    console.info(`IVI [${VERSION}]: DEVELOPMENT MODE`);
                         ^^^^^^^

stdin:6247: ERROR - variable printError is undeclared
        printError("`Array.isArray` function is missing.");
        ^^^^^^^^^^

stdin:6262: ERROR - variable FEATURES is undeclared
        console.groupCollapsed(`${((FEATURES & flag) ? "✔" : "✖")} ${name}`);
                                    ^^^^^^^^

stdin:6286: ERROR - variable findVNodeByDebugId is undeclared
        "findVNodeByDebugId": findVNodeByDebugId,
                              ^^^^^^^^^^^^^^^^^^

stdin:6287: ERROR - variable findVNodeByNode is undeclared
        "findVNodeByNode": findVNodeByNode,
                           ^^^^^^^^^^^^^^^

stdin:6290: ERROR - variable visitComponents is undeclared
                visitComponents(_printComponentTreeVisitor);
                ^^^^^^^^^^^^^^^

stdin:6309: ERROR - variable GLOBAL_EXPORT is undeclared
    if (GLOBAL_EXPORT && !window.hasOwnProperty(GLOBAL_EXPORT)) {
        ^^^^^^^^^^^^^

29 error(s), 0 warning(s)

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ivi-boilerplate@1.0.0 dist: `webpack --config webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ivi-boilerplate@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sk/.npm/_logs/2017-08-25T08_13_14_376Z-debug.log
```

npm run serve
seems to work fine.

**Comment by localvoid** [comment]
It seems that latest closure compiler versions started to perform checks inside of a dead code. This is one of the reasons why I've moved away from `DefinePlugin` and now using [ivi-vars](https://github.com/ivijs/ivi/tree/master/packages/ivi-vars) package and `resolve.alias` to change settings.

It can be fixed by disabling errors in closure compiler config `jscomp_off: "*"`
